baseURL = 'https://icejardins.org.br/'
languageCode = 'pt-br'
title = 'ICE Jardins - Igreja Cristã Evangélica Jardins'
theme = 'hugo-profile'
enableRobotsTXT = true
hasCJKLanguage = false

defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "RSS"]

[pagination]
    pagerSize = 10

[languages]
  [languages.pt]
    languageName = 'Português'
    contentDir = 'content'
    weight = 1

[params]
  favicon = "/images/fav.png"
  animate = true

[params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

[params.navbar]
    align = "ms-auto"
    brandName = "Igreja Cristã Evangélica Jardins"
    disableSearch = false
    enableSeparator = false

[params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

[params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

[params.contact]
    enable = true
    content = "Nossa equipe de atendimento está à disposição para responder suas perguntas, ouvir suas necessidades e orientar você em qualquer questão espiritual. Enviamos mensagens e bênçãos por todos os meios disponíveis para abençoar sua vida."
    btnName = "Fale conosco"
    btnLink = "mailto:secretaria@icejardins.org.br"

[params.footer.recentPosts]
    path = "blogs"
    count = 3
    title = "Publicações recentes"
    enable = true
    disableFeaturedImage = false

[params.footer.socialNetworks]
    facebook = "https://www.facebook.com/icejardins/"
    instagram = "https://www.instagram.com/icejardins/"
    whatsapp = "https://wa.me/5561982624952"

[params.datesFormat]
    article = "January 2, 2006"
    articleList = "January 2, 2006"
    articleRecent = "January 2, 2006"

[taxonomies]
    category = "categorias"
    tag = "tags"
    series = "series"

[permalinks]
    posts = "/:year/:month/:title/"

[[menu.main]]
    name = "Início"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 2

[[menu.main]]
    name = "Visita"
    url = "/visita/"
    weight = 3

[[menu.main]]
    name = "No que cremos"
    url = "/fe/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
